### ISSUE TITLE
errors in satellite 6.4

### ISSUE THREAD

**Issue by buckljc2** [gerbron/satellite6-content_views#1]
Not sure it's really an issue since we resolved it, but we had to modify the update_composite_view, remove_content_view and publish_content_view files to remove the leading /v2 from the path in order for the role to work with our version of satellite 6.4.  

That was per the API docs, the path no longer uses /v2/content_views

**Comment by buckljc2** [comment]
Thanks for the role, works like a champ!

**Comment by ogerbron** [comment]
Hi there, and sorry for the late reply.

I must admit I haven't been using Satellite for a while since I moved to another job ! 

Sorry about the error, I'll put that in a variable instead, it'll be easier to modify.

Good to hear you liked the role :+1:
